spring:
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: pass123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

message: Hello, Department Service